#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleDeProjetos.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ControleDeProjeto")]
	public partial class ControleDeProjetosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ControleDeProjetosDataContext() : 
				base(global::ControleDeProjetos.DAL.Properties.Settings.Default.ControleDeProjetoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ControleDeProjetosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ControleDeProjetosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ControleDeProjetosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ControleDeProjetosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetFornecedores")]
		public ISingleResult<GetFornecedoresResult> GetFornecedores()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetFornecedoresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetFornecedoresByNome")]
		public ISingleResult<GetFornecedoresByNomeResult> GetFornecedoresByNome([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nome", DbType="VarChar(50)")] string nome)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nome);
			return ((ISingleResult<GetFornecedoresByNomeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUsuarioByLogin")]
		public ISingleResult<GetUsuarioByLoginResult> GetUsuarioByLogin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string senha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, senha);
			return ((ISingleResult<GetUsuarioByLoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GravaUsuario")]
		public ISingleResult<GravaUsuarioResult> GravaUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nome", DbType="VarChar(255)")] string nome, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Senha", DbType="VarChar(255)")] string senha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoUsuario", DbType="VarChar(5)")] string tipoUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nome, email, senha, tipoUsuario);
			return ((ISingleResult<GravaUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUsuarios")]
		public ISingleResult<GetUsuariosResult> GetUsuarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetUsuariosResult>)(result.ReturnValue));
		}
	}
	
	public partial class GetFornecedoresResult
	{
		
		private System.Guid _IDFornecedor;
		
		private string _FornecedorNome;
		
		public GetFornecedoresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFornecedor", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IDFornecedor
		{
			get
			{
				return this._IDFornecedor;
			}
			set
			{
				if ((this._IDFornecedor != value))
				{
					this._IDFornecedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FornecedorNome", DbType="VarChar(50)")]
		public string FornecedorNome
		{
			get
			{
				return this._FornecedorNome;
			}
			set
			{
				if ((this._FornecedorNome != value))
				{
					this._FornecedorNome = value;
				}
			}
		}
	}
	
	public partial class GetFornecedoresByNomeResult
	{
		
		private System.Guid _IDFornecedor;
		
		private string _FornecedorNome;
		
		public GetFornecedoresByNomeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFornecedor", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IDFornecedor
		{
			get
			{
				return this._IDFornecedor;
			}
			set
			{
				if ((this._IDFornecedor != value))
				{
					this._IDFornecedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FornecedorNome", DbType="VarChar(50)")]
		public string FornecedorNome
		{
			get
			{
				return this._FornecedorNome;
			}
			set
			{
				if ((this._FornecedorNome != value))
				{
					this._FornecedorNome = value;
				}
			}
		}
	}
	
	public partial class GetUsuarioByLoginResult
	{
		
		private string _Nome;
		
		private string _TipoUsuario;
		
		public GetUsuarioByLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoUsuario", DbType="VarChar(5)")]
		public string TipoUsuario
		{
			get
			{
				return this._TipoUsuario;
			}
			set
			{
				if ((this._TipoUsuario != value))
				{
					this._TipoUsuario = value;
				}
			}
		}
	}
	
	public partial class GravaUsuarioResult
	{
		
		private string _Nome;
		
		private string _TipoUsuario;
		
		public GravaUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoUsuario", DbType="VarChar(5)")]
		public string TipoUsuario
		{
			get
			{
				return this._TipoUsuario;
			}
			set
			{
				if ((this._TipoUsuario != value))
				{
					this._TipoUsuario = value;
				}
			}
		}
	}
	
	public partial class GetUsuariosResult
	{
		
		private System.Guid _ID;
		
		private string _Nome;
		
		private string _Email;
		
		private string _TipoUsuario;
		
		private System.Nullable<System.DateTime> _DtCadastro;
		
		private System.Nullable<bool> _Ativo;
		
		public GetUsuariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(255)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoUsuario", DbType="VarChar(5)")]
		public string TipoUsuario
		{
			get
			{
				return this._TipoUsuario;
			}
			set
			{
				if ((this._TipoUsuario != value))
				{
					this._TipoUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DtCadastro", DbType="DateTime")]
		public System.Nullable<System.DateTime> DtCadastro
		{
			get
			{
				return this._DtCadastro;
			}
			set
			{
				if ((this._DtCadastro != value))
				{
					this._DtCadastro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit")]
		public System.Nullable<bool> Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this._Ativo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
